# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'opentok' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for opentok
  pod 'OpenTok', '2.15.3'

  target 'opentok-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end


end

target 'opentok-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!


end
